#!/bin/bash
set -eu
THIS="$(readlink -f "$0")"
THISDIR="$(dirname "${THIS}")"
SUT="$(dirname "${THISDIR}")/makeself.sh"

setupTests() {
  temp=$(mktemp -d -t XXXXX)
  pushd "${temp}"
  mkdir -p src/.git
  echo "echo This is a test" > src/startup.sh
}

tearDown() {
  popd
  rm -rf "${temp}"
}

testTarExtraOpts() {
  setupTests

  tar_extra="--verbose --exclude .git"
  ${SUT} --tar-extra "$tar_extra" src src.sh alabel startup.sh

  assertEquals $? 0

  tearDown
}

# Load and run shUnit2.
source "./shunit2/shunit2"

