#!/usr/bin/env bash

SUT=$(realpath $(dirname $0)/../makeself.sh)
SOURCE=$(realpath ..)

setupTests() {
  temp=`mktemp -d -t XXXXX`
  cd "$temp"
  mkdir archive
  touch archive/file

  $SUT archive makeself-test.run "Test $1" declare -p "${1}"
}

testArchiveDir()
{
  setupTests ARCHIVE_DIR
  local ans=$'./complicated\n dir\twith  spaces'
  mkdir "${ans}"
  mv ./makeself-test.run "${ans}/"
  actual_archive_dir="$("${ans}/makeself-test.run" --quiet)"

  ans="$(export ARCHIVE_DIR="${ans}"; declare -p ARCHIVE_DIR)"
  assertEqual "${actual_archive_dir}" "${ans}"
}

source bashunit/bashunit.bash
